### ISSUE TITLE
Create Sample Application

### ISSUE THREAD

**Issue by SMK1085** [SMK1085/ng2-adal#2]
Create a sample angular2 application to demonstrate functionality.

**Comment by isaacrlevin** [comment]
Is this project still active? There is another project that is doing something similar

https://github.com/sureshchahal/angular2-adal

**Comment by SMK1085** [comment]
I am "migrating" it into a new project, @isaac2004. The new project does not depend on the adaljs lib and will be compatible with the Microsoft graph v2 endpoint.

**Comment by isaacrlevin** [comment]
Interesting... so I imagine it will still authenticate against Azure AD Apps? Any time line for an initial release?

**Comment by MikeLallemont** [comment]
How can I add this using webpack? Any example code would be greatly appreciated. I'm trying to integrate this with ionic 20.0.rc-1 and angular 2.0.0.
